name: Main
on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup
      - name: Run test
        run: yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup
      - name: Lint
        run: yarn lint

  check_types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup
      - name: Check types
        run: yarn check:types

  build_lib:
    name: Build lib
    runs-on: ubuntu-latest
    needs: [test, lint, check_types]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup
      - name: Building the libs
        run: yarn build:all