name: Features branches

on:
  push:
    branches:
      - '!main'
      - '!dev'
  pull_request:
    branches:
      - '!main'
      - '!dev'

jobs:
  test:
    uses: ./.github/workflows/test-workflow.yml