name: Main

on:
  push:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build_lib:
    name: Build lib
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup
      - name: Building the libs
        run: yarn build:all

  test_bundle:
    name: Test bundle
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup
      - name: Building the libs
        run: yarn test:bundle