name: Main

on:
  push:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build_lib:
    name: Build lib
    runs-on: ubuntu-latest
    needs: [ test, lint, check_types ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup
      - name: Building the libs
        run: yarn build:all