name: Main & Dev

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    uses: ./.github/workflows/test-workflow.yml

  build_lib:
    name: Build lib
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup

      - name: Building the libs
        run: yarn build:all

      - name: Upload artifacts for core/lib
        uses: actions/upload-artifact@v3
        with:
          name: core_lib
          path: ./packages/core/lib

      - name: Upload artifacts for parser/lib
        uses: actions/upload-artifact@v3
        with:
          name: parser_lib
          path: ./packages/parser/lib

      - name: Upload artifacts for generix/lib
        uses: actions/upload-artifact@v3
        with:
          name: generix_lib
          path: ./packages/generix/lib

  test_bundle:
    name: Test bundle
    runs-on: ubuntu-latest
    needs: [ build_lib ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup

      - name: Download core/lib artifact
        uses: actions/download-artifact@v3
        with:
          name: core_lib
          path: packages/core/lib

      - name: Download parser/lib artifact
        uses: actions/download-artifact@v3
        with:
          name: parser_lib
          path: packages/parser/lib

      - name: Download generix/lib artifact
        uses: actions/download-artifact@v3
        with:
          name: generix_lib
          path: packages/generix/lib

      - name: Testing the bundle
        run: yarn test:bundle
